/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_api_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_api_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent */
        delete: operations["delete_agent_api_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_api_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rooms
         * @description Every room this user owns, newest first, each with its roster.
         *
         *     The roster comes along because the lobby draws the agents on every card.
         *     Returning bare rooms would make the first screen a user sees issue one
         *     request per room to fill itself in.
         */
        get: operations["list_rooms_api_rooms_get"];
        put?: never;
        /** Create Room */
        post: operations["create_room_api_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Room */
        get: operations["get_room_api_rooms__room_id__get"];
        put?: never;
        post?: never;
        /** Delete Room */
        delete: operations["delete_room_api_rooms__room_id__delete"];
        options?: never;
        head?: never;
        /** Update Room */
        patch: operations["update_room_api_rooms__room_id__patch"];
        trace?: never;
    };
    "/api/rooms/{room_id}/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add Agent
         * @description Seat an agent at this roundtable.
         *
         *     PUT rather than POST: seating an agent twice is the same as seating it
         *     once, and a client retrying a dropped request should not be punished.
         */
        put: operations["add_agent_api_rooms__room_id__agents__agent_id__put"];
        post?: never;
        /** Remove Agent */
        delete: operations["remove_agent_api_rooms__room_id__agents__agent_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description A page of the transcript, in order.
         *
         *     An empty page for a room that does not exist would be indistinguishable
         *     from an empty room, so the room is checked first.
         */
        get: operations["list_messages_api_rooms__room_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Run the room, streaming each event as it happens.
         */
        post: operations["start_run_api_rooms__room_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Key
         * @description Ask OpenRouter whether this key works. Runs no inference.
         */
        post: operations["validate_key_api_keys_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage Daily
         * @description Spending per day, oldest first, with quiet days included as zero.
         *
         *     The zeroes matter. A chart that plots only the days with activity draws a
         *     continuous line through a fortnight of nothing, which reads as steady
         *     spending rather than as a gap.
         *
         *     Days are UTC, matching how ``created_at`` is stored. A user in another
         *     timezone sees a boundary that is not their midnight; correcting that needs
         *     their offset, which is worth asking for only once anyone is reconciling
         *     these numbers against an invoice.
         */
        get: operations["usage_daily_api_usage_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage By Room
         * @description Per-room spending over a window, most expensive first.
         */
        get: operations["usage_by_room_api_usage_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage Events
         * @description This caller's most recent provider calls, newest first.
         *
         *     The room name and the speaker are embedded rather than resolved by the
         *     client, which would otherwise issue a request per row. Both can be null:
         *     usage deliberately outlives the room and the message it came from, because
         *     deleting a room must not erase the record of money already spent.
         */
        get: operations["usage_events_api_usage_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usage Summary
         * @description Summarise this caller's usage.
         *
         *     Aggregated in Python rather than SQL: the row counts here are small — one
         *     per provider request per user — and a database function would be a second
         *     place for the definition of "cost" to live and drift.
         */
        get: operations["usage_summary_api_usage_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{agent_id}/builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Agent
         * @description Take one turn of the conversation that writes an agent's instructions.
         */
        post: operations["build_agent_api_agents__agent_id__builder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentIn */
        AgentIn: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** System Prompt */
            system_prompt: string;
            /**
             * Enabled Tools
             * @description Null means the defaults. An empty list means no tools.
             */
            enabled_tools?: string[] | null;
        };
        /** AgentOut */
        AgentOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** System Prompt */
            system_prompt: string;
            /** Enabled Tools */
            enabled_tools: string[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentPatch */
        AgentPatch: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Enabled Tools */
            enabled_tools?: string[] | null;
        };
        /** BuilderMessage */
        BuilderMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** BuilderRequest */
        BuilderRequest: {
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
            /** Conversation */
            conversation?: components["schemas"]["BuilderMessage"][];
            /**
             * Model
             * @default qwen/qwen3.7-flash
             */
            model: string;
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Instructions */
            instructions?: string | null;
        };
        /** BuilderResponse */
        BuilderResponse: {
            /** Reply */
            reply: string;
            /** Instructions */
            instructions: string | null;
            /** Needs Answer */
            needs_answer: boolean;
            /** Cost Usd */
            cost_usd?: number | null;
        };
        /**
         * DailyUsage
         * @description One day's spending, for the chart on the billing screen.
         */
        DailyUsage: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Requests */
            requests: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /**
         * Emitter
         * @description Who produced a message. Drives how it renders into Supervisor context.
         * @enum {string}
         */
        Emitter: "user" | "agent" | "supervisor" | "system";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** KeyCheckRequest */
        KeyCheckRequest: {
            /**
             * Api Key
             * Format: password
             */
            api_key: string;
        };
        /** KeyCheckResponse */
        KeyCheckResponse: {
            /** Valid */
            valid: boolean;
            /** Message */
            message: string;
            /** Is Free Tier */
            is_free_tier?: boolean | null;
            /**
             * Limit Remaining
             * @description Credit left on this key, when the key carries a limit.
             */
            limit_remaining?: number | null;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: string;
            /** Seq */
            seq: number;
            emitter: components["schemas"]["Emitter"];
            /** Emitter Name */
            emitter_name: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessagePage
         * @description A page of transcript.
         *
         *     Paged by ``seq`` rather than an offset. A transcript grows while it is
         *     being read, and an offset would skip or repeat messages as it does.
         */
        MessagePage: {
            /** Items */
            items: components["schemas"]["MessageOut"][];
            /**
             * Next After Seq
             * @description Pass as after_seq to continue. Null when the page is the last.
             */
            next_after_seq?: number | null;
        };
        /**
         * RoomDetailOut
         * @description A room together with its roster.
         *
         *     Returned as one object because the interface always needs both, and asking
         *     for them separately is a round trip the room view would make every time.
         */
        RoomDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Objective */
            objective: string;
            status: components["schemas"]["RoomStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Agents */
            agents: components["schemas"]["AgentOut"][];
        };
        /** RoomIn */
        RoomIn: {
            /** Name */
            name: string;
            /** Objective */
            objective: string;
            /**
             * Agent Ids
             * @description Agents to seat at this roundtable.
             */
            agent_ids?: string[];
        };
        /** RoomOut */
        RoomOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Objective */
            objective: string;
            status: components["schemas"]["RoomStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RoomPatch */
        RoomPatch: {
            /** Name */
            name?: string | null;
            /** Objective */
            objective?: string | null;
            /** @description Set to paused to stop this room accepting new runs. */
            status?: components["schemas"]["RoomStatus"] | null;
        };
        /**
         * RoomStatus
         * @description Whether a room will accept a new run.
         *
         *     Pausing exists so that stopping the spending on a room does not mean
         *     deleting it. A paused room keeps its roster and its transcript; it just
         *     refuses to start.
         * @enum {string}
         */
        RoomStatus: "active" | "paused";
        /**
         * RoomUsage
         * @description What one room has cost its owner.
         *
         *     The lobby shows this on every card, so it is one request for every room
         *     rather than one per room. Rooms with no recorded usage are absent, which
         *     the caller reads as zero — storing a zero row for a room nobody has run
         *     would be inventing a fact.
         */
        RoomUsage: {
            /** Room Id */
            room_id: string;
            /** Requests */
            requests: number;
            /** Cost Usd */
            cost_usd: number;
            /** Unpriced Requests */
            unpriced_requests: number;
            /** Cost Is Complete */
            cost_is_complete: boolean;
            /** Last Active At */
            last_active_at: string | null;
        };
        /**
         * RunRequest
         * @description What starting a run needs.
         *
         *     The key is typed as a secret so that anything which stringifies this model
         *     — a validation error, a log line, an exception repr — masks it rather than
         *     printing it.
         */
        RunRequest: {
            /**
             * Api Key
             * Format: password
             * @description The caller's own OpenRouter key.
             */
            api_key: string;
            /**
             * Model
             * @default anthropic/claude-sonnet-4.5
             */
            model: string;
            /** Max Turns */
            max_turns?: number | null;
            /** Spend Cap Usd */
            spend_cap_usd?: number | null;
        };
        /**
         * UsageEventOut
         * @description One provider call, as the audit log shows it.
         */
        UsageEventOut: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Model */
            model: string;
            /** Room Id */
            room_id: string | null;
            /**
             * Room Name
             * @description Null when the room has since been deleted; the spending still happened.
             */
            room_name?: string | null;
            /**
             * Emitter Name
             * @description Who was speaking when this was spent.
             */
            emitter_name?: string | null;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /**
             * Cost Usd
             * @description Null when the provider did not price the call.
             */
            cost_usd?: number | null;
        };
        /**
         * UsageSummary
         * @description A user's own spending over a window.
         */
        UsageSummary: {
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Rooms
             * @description Rooms that saw activity in this window.
             */
            rooms: number;
            /** Requests */
            requests: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /**
             * Cost Usd
             * @description What the provider reported, summed.
             */
            cost_usd: number;
            /**
             * Unpriced Requests
             * @description Requests the provider did not price. The cost above is a floor rather than a total when this is above zero.
             */
            unpriced_requests: number;
            /** Cost Is Complete */
            cost_is_complete: boolean;
            /**
             * Tool Enabled Requests
             * @description Requests that could reach the web.
             */
            tool_enabled_requests: number;
            /**
             * Tool Enabled Cost Usd
             * @description Reported cost of those requests. A web search costs roughly forty times the tokens of a room, so this is where spending actually comes from.
             */
            tool_enabled_cost_usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_agents_api_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
        };
    };
    create_agent_api_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rooms_api_rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDetailOut"][];
                };
            };
        };
    };
    create_room_api_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_room_api_rooms__room_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_room_api_rooms__room_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_room_api_rooms__room_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_agent_api_rooms__room_id__agents__agent_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_agent_api_rooms__room_id__agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_rooms__room_id__messages_get: {
        parameters: {
            query?: {
                after_seq?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_rooms__room_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_key_api_keys_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_daily_api_usage_daily_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyUsage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_by_room_api_usage_rooms_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomUsage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_events_api_usage_events_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_summary_api_usage_summary_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_agent_api_agents__agent_id__builder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuilderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuilderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
